import type { Metadata } from 'next'
import { Inter, IBM_Plex_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/shared/providers/theme-provider'

const sans = Inter({
	variable: '--font-sans',
	subsets: ['latin', 'cyrillic']
})

const mono = IBM_Plex_Mono({
	weight: ['400', '500', '600', '700'],
	variable: '--font-mono',
	subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
	title: 'Ivan Pavlovich | Frontend Developer',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className={`${sans.variable} ${mono.variable} h-full antialiased`}
			suppressHydrationWarning
		>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
